### ISSUE TITLE
no love for npm run start

### ISSUE THREAD

**Issue by karlcow** [miketaylr/compat-dashboard#3]
```
du -h .
128 K

→ npm -v
1.4.21
→ npm install

du -h .
83 M

# Sniff sniff

→ npm run start

> compat-dashboard@1.0.0 start /Users/karl/code/compat-dashboard
> react-scripts start


/Users/karl/code/compat-dashboard/node_modules/react-scripts/scripts/start.js:23
var isSmokeTest = process.argv.some(arg =>
                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by magsout** [comment]
@karlcow npm version is too old

> You’ll need to have Node >= 4 on your machine. We recommend to use Node >= 6 and npm >= 3 for faster installation speed and better disk usage. You can use nvm to easily switch Node versions between different projects.

**Comment by karlcow** [comment]
woot. I just upgraded from HTML+ to HTML2.0

**Comment by karlcow** [comment]
time to clean up things

```
→ locate npm | grep npm/bin/npm
/Users/karl/.nvm/versions/node/v4.0.0/lib/node_modules/npm/bin/npm
/Users/karl/.nvm/versions/node/v4.0.0/lib/node_modules/npm/bin/npm-cli.js
/Users/karl/.nvm/versions/node/v4.0.0/lib/node_modules/npm/bin/npm.cmd
/Users/karl/code/node/deps/npm/bin/npm
/Users/karl/code/node/deps/npm/bin/npm-cli.js
/Users/karl/code/node/deps/npm/bin/npm.cmd
/usr/local/lib/node_modules/npm/bin/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib/node_modules/npm/bin/npm.cmd
19:46:20 ~/code/compat-dashboard
→ which npm
/usr/local/bin/npm

```

**Comment by karlcow** [comment]
resolved by @magsout
